# Generated by Django 5.1.6 on 2025-02-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["name"], name="api_author_name_076641_idx"),
        ),
    ]
