# Generated by Django 5.1.6 on 2025-02-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_post_api_post_author__3bc35e_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["created_at"], name="api_post_created_a6ef6d_idx"
            ),
        ),
    ]
